version: "2"
sql:
  - engine: "postgresql"
    queries: "internal/db/query.sql"
    schema: "internal/db/migrations"
    gen:
      go:
        package: "db"
        out: "internal/db"
        emit_json_tags: true
        json_tags_case_style: "camel"
