version: "2"
sql:
  - engine: "postgresql"
    queries: "db/postgres/query.sql"
    schema: "migrations/postgres"
    gen:
      go:
        package: "postgres"
        out: "db/postgres"
        emit_json_tags: true
  - engine: "sqlite"
    queries: "db/sqlite/query.sql"
    schema: "migrations/sqlite"
    gen:
      go:
        package: "sqlite"
        out: "db/sqlite"
        emit_json_tags: true
