version: "2"
plugins:
- name: ts
  wasm:
    url: https://downloads.sqlc.dev/plugin/sqlc-gen-typescript_0.1.3.wasm
    sha256: 287df8f6cc06377d67ad5ba02c9e0f00c585509881434d15ea8bd9fc751a9368
sql:
  - engine: "postgresql"
    queries: "pkg/db/query.sql"
    schema: "pkg/db/migrations"
    codegen:
    - out: web/db
      plugin: ts
      options:
        runtime: node
        driver: postgres
    gen:
      go:
        package: "db"
        out: "pkg/db"
        emit_json_tags: true
        json_tags_case_style: "camel"
