services:
  db:
    image: postgres:18
    container_name: db
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=borg
      - POSTGRES_USER=borg
      - POSTGRES_PASSWORD=changeme
  app:
    build: .
    container_name: app
    environment:
      - DATABASE_URL
      - APP_ENV
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db:
