services:
  db:
    image: postgres:18-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=borg
      - POSTGRES_USER=borg
      - POSTGRES_PASSWORD=borg

volumes:
  db:
