services:
  db:
    image: postgres:18
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=llamap
      - POSTGRES_PASSWORD=changeme
  app:
    build: .
    container_name: app
    environment:
      - DATABASE_URL
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db:
