/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * OpenAPI spec version: 0.0.1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface User {
  id?: number;
  username?: string;
  /** @nullable */
  bio?: string | null;
  followersCount?: number;
  followingCount?: number;
  isAdmin?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * @summary Get a user by ID
 */
export const getApiUsersId = <TData = AxiosResponse<User>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users/${id}`,options
    );
  }

export type GetApiUsersIdResult = AxiosResponse<User>
