services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DATABASE_URL
      - APP_ENV
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
        - external_network
        - internal_network
  db:
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=borg
      - POSTGRES_USER=borg
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
        - internal_network

volumes:
  postgres-data:

networks:
  external_network:
  internal_network:
    internal: true
