/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * OpenAPI spec version: 0.0.1
 */

export type UserAllOf = {
  id: number;
  origin: string;
  readonly followersCount: number;
  readonly followingCount: number;
  createdAt: string;
  updatedAt: string;
};
