/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * OpenAPI spec version: 0.0.1
 */

export interface User {
  id?: number;
  username?: string;
  /** @nullable */
  bio?: string | null;
  followersCount?: number;
  followingCount?: number;
  isAdmin?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
