/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * Borg OpenAPI specification
 * OpenAPI spec version: 0.0.1
 */

export interface User {
  id: number;
  username: string;
  bio: string;
  origin: string;
  isAdmin: boolean;
  followersCount: number;
  followingCount: number;
  createdAt: string;
  updatedAt: string;
}
