/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * Borg OpenAPI specification
 * OpenAPI spec version: 0.0.1
 */
import type { NewUser } from './newUser';
import type { UpdateUser } from './updateUser';
import type { UserAllOf } from './userAllOf';

export type User = NewUser & UpdateUser & UserAllOf & Required<Pick<NewUser & UpdateUser & UserAllOf, 'bio' | 'isAdmin'>>;
