name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'

      - name: Prepare embedded assets
        run: mkdir -p web/dist && touch web/dist/index.html

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v8

  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node dependencies
        run: pnpm run ci
        working-directory: web

      - name: Format with biome
        working-directory: web
        run: pnpm run format 

      - name: Check with biome
        working-directory: web
        run: pnpm run check
